family: sd
sd:
  variant: objaverse
  v2_highres: false
  prompt: a photograph of an astronaut riding a horse
  im_path: data/nerf_synthetic/chair/train/r_2.png
  scale: 100.0
  precision: autocast
lr: 0.05
n_steps: 10000
vox:
  model_type: V_SD
  bbox_len: 1.0
  grid_size:
  - 100
  - 100
  - 100
  step_ratio: 0.5
  density_shift: -1.0
  ray_march_weight_thres: 0.0001
  c: 4
  blend_bg_texture: false
  bg_texture_hw: 4
pose:
  rend_hw: 32
  FoV: 60.0
  R: 0.5
  up: z
emptiness_scale: 10
emptiness_weight: 0
emptiness_step: 0.5
emptiness_multiplier: 20.0
grad_accum: 1
depth_smooth_weight: 100000.0
near_view_weight: 100000.0
depth_weight: 0
var_red: true
train_view: true
scene: B07B4MMV3N
index: 0
view_weight: 10000
prefix: exp
nerf_path: data/sofa
